---
# file for test ansbibe playbook for aci tenant
- name: Play Create the Demo Tenant
  hosts: servers
  gather_facts: no

  tasks:
  - name: Add a new tenant
    cisco.aci.aci_tenant:
      host: "{{ansible_host}}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "Fabios_Tenant"
      description: "WLAN_tenant"
      state: present
    delegate_to: localhost
    register: log

  - name: Test task in tenants
    ansible.builtin.debug:
      msg: "tenant done"
# register with debug prints return values for the tenant
  - debug: var=log

  